#!/bin/bash

echo ""
echo " The AppImageKit Toolbox is a 'Meta'-AppImage containing almost all of the tools developed by the AppImage project"
echo " contributors. These tools themselves are mostly AppImages themselves. They serve to create and dissect/extract"
echo " AppImages, if they are meant to be used interactively by users. Others (like 'AppRun' or 'runtime') are meant to"
echo " be embedded inside in order to make an AppImage work as it should."
echo ""
echo " Usage:   $ARGV0  <sub-command>"
echo ""
echo "   Available sub-commands:"
echo ""
echo "      AppImageUpdate        :  GUI tool to search for and apply binary delta updates to existing AppImages"
echo "      appimageupdatetool    :  CLI tool to search for and apply binary delta updates to existing AppImages"
echo "      appimaged             :  Daemon to integrate AppImages into desktop environment (provide menu entries + icons"
echo "      appimagetool          :  Tool to create AppImages from AppDirs and to dissect and inspect them"
echo "      linuxdeployqt         :  Tool to optimize AppDirs and automatically bundle in all libraries required by its binaries"
echo "      zsync2                :  Tool to easily update files to newer versions via highly efficient 'delta' updates"
echo "      zsyncmake2            :  Tool to create 'foo.zsync' file for existing 'foo' file for later update via zsync2"
echo ""
echo "   Other executables included:"
echo ""
echo "      [AppRun]              :  Not meant to be run by users -- to be included into an AppImage to make it work"
echo "      [runtime]             :  Not meant to be run by users -- to be included into an AppImage to make it work"
echo ""
echo "      {upload.sh}           :  Script to..."
echo "      {bintray.sh}          :  Script to..."
echo "      {functions.sh}        :  Script to..."
echo "      {appdir-lint.sh}      :  Script to..."
echo "      {set-up-ppas.sh}      :  Script to..."
echo "      {testappimage.sh}     :  Script to..."
echo "      {pkg2appimage.sh}     :  Script to..."
echo "      {bintray-tidy.sh}     :  Script to..."
echo "      {testappimage-tool.sh}               :  Script to..."
echo "      {travistriggerbuilds.sh}             :  Script to..."
echo "      {test-appimage-on-many-live-isos.sh} :  Script to..."
echo "      {travisbuild-with-without-docker.sh} :  Script to..."
echo ""
echo " [foo] = standard ELF binary;      {bar} = Bash script;      Rest = AppImage"
echo ""
